language: php

php:
    - '7.2'
    - '7.3'
    - '7.4'

install:
    - composer install --prefer-dist --no-interaction --no-progress

script:
    - vendor/bin/phpunit
    - vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no .

after_script:
    - vendor/bin/phpbench run --report=aggregate --retry-threshold=2 --progress=dots
