language: php

php:
    - '7.2'
    - '7.3'

install:
    - composer install --prefer-dist --no-interaction --no-progress

script:
    - vendor/bin/phpunit
    - vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation --using-cache=no
