name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test-suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
    steps:
    - uses: actions/checkout@v2
    - name: Run manifest validation
      run: composer validate
    - name: Run package caching
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Run package installation
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run test suite
      run: vendor/bin/phpunit --coverage-text
  benchmark-suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
    steps:
    - uses: actions/checkout@v2
    - name: Run manifest validation
      run: composer validate
    - name: Run package caching
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Run package installation
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run benchmark suite
      run: vendor/bin/phpbench run --report=aggregate --retry-threshold=2 --progress=dots
  code-standards-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run manifest validation
      run: composer validate
    - name: Run package caching
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Run package installation
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run code standards checking
      run: vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no .
  code-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run manifest validation
      run: composer validate
    - name: Run package caching
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Run package installation
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run code analysis
      uses: codacy/codacy-analysis-cli-action@1.1.0
  code-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run manifest validation
      run: composer validate
    - name: Run package caching
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Run package installation
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run code coverage
      uses: codacy/codacy-coverage-reporter-action@0.2.0